name: "build"
on: [push, workflow_dispatch]

env:
  EM_VERSION: 3.1.43
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: foo
      - name: Instal pkg-config
        run: |
          conda install -y -c conda-forge pkg-config;
          pkg-config --version;
      - name: Build library
        run: |
          emcc --version;
          cmake --version;
          make;
      - uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: plugins/*
